global:
  smtp_smarthost: ''
  smtp_from: ''
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true

route:
  receiver: ''

receivers:
  - name: ''
    email_configs:
      - to: ''